version: '3.4'
services:
   db:
      image: murilofelpeto/natal-database
      command: mongod --logpath=/dev/null # --quiet
      restart: always
      build:
         context: .
         dockerfile: containers/db/Dockerfile
      environment:
         - MONGO_INITDB_ROOT_USERNAME=docker
         - MONGO_INITDB_ROOT_PASSWORD=docker
         - MONGO_INITDB_DATABASE=wsoauth2
      ports:
         - 27017:27017
      networks:
         - crawler-network
   application:
      image: murilofelpeto/natal-americanas-crawler
      restart: always
      build:
         context: .
         dockerfile: containers/app/Dockerfile
      working_dir: /data/api
      environment:
         TZ: America/Sao_Paulo
         SPRING_BOOT_ENVIRONMENT: Production
      volumes:
         - ./:/data/api
         - ~/.m2:/root/.m2
      command: mvn clean spring-boot:run
      ports:
         - 8080:8080
      links:
         - db
      depends_on:
         - db
      networks:
         - crawler-network
networks:
   crawler-network:
      driver: bridge